author: Ex Cinere Surgimus
database: false
description: "Bukkit plugin for a ban-less punishment system.\r\n"
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.excineresurgimus.plugins.favordisfavor.Favordisfavor
name: Favor-Disfavor
startup: postworld
url: http://www.ecs-server.net/
version: '1.0'
commands:
  favorite:
    description: "Favorites a person."
    permission: favordisfavor.favor
  disfavorite:
    description: "Disfavorites a person."
    permission: favordisfavor.disfavor
  getvalue:
    description: "Returns favoritism value."
    permission: favordisfavor.getvalue